config/routes.rb
Rails.application.routes.draw do
  get 'shops/index'
  get 'shops/show'
  get 'shops/new'
  get 'shops/register'
  get 'shops/logged_in'
  get 'shops/not_logged_in'
  get 'shops/setting'
  get 'shops/result'
  get 'shops/detail/:shopid' => 'shops#detail'
  get 'sessions/new'
  get 'main/index'
  get 'main/show'
  get 'users/index'
  get 'users/show'
  get 'users/register'
  get 'users/new'
  get 'users/logged_in'
  get 'users/not_logged_in'
  get 'users/break'
  get 'users/break_out'
  get 'users/setting'
  post 'users' => 'users#register'
  post 'shops' => 'shops#register'
  post 'shops/new' => 'shops#create'
  post 'shops/setting' => 'shops#update'
  patch '/shops/setting' => 'shops#update'
  put '/shops/setting' => 'shops#update'
  post 'users/new' => 'users#create'
  post 'users/setting' => 'users#update'
  patch '/users/setting' => 'users#update'
  put '/users/setting' => 'users#update'
  get 'users/show/:user_id' => "users#show"
  get    'users/logged_in',   to: 'sessions#new'
  post   'users/logged_in',   to: 'sessions#create'
  delete 'users/not_logged_in',  to: 'sessions#destroy'
  get    'shops/logged_in',   to: 'sessions#new'
  post   'shops/logged_in',   to: 'sessions#create'
  delete 'shops/not_logged_in',  to: 'sessions#shop_destroy'
  get 'users/break_out', to:'sessions#taikaiout'
  get 'users/break_zumi'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_one_attached :image
    has_secure_password
    
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/user_hide.rb
class UserHide < ApplicationRecord
    has_one_attached :image
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    
    # ログイン済みユーザーかどうか確認
    def logged_in_user
        unless logged_in?
            redirect_to "/sessions/new"
        end
    end
    def shop_logged_in_user
        unless shop_logged_in?
            redirect_to "/sessions/new"
        end
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def show
    @home = Hash.new
    @home[:welcome] = "ようこそBarBarEatsへ"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    shop = Shop.find_by(email: params[:session][:email].downcase)
    user = UserHide.find_by(email: params[:session][:email].downcase)
    if shop == nil
      if user == nil
        redirect_to "/sessions/new"
      elsif false == user.break
        redirect_to "/users/break_zumi"
      elsif user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to users_logged_in_path(user: user)
      else
        redirect_to "/sessions/new"
      end
    else
      if false == shop.break
        redirect_to "/users/break_zumi"
      elsif shop && shop.authenticate(params[:session][:password])
        shop_log_in shop
        redirect_to shops_logged_in_path(shop: shop)
      else
        redirect_to "/sessions/new"
      end
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to "/users/not_logged_in"
  end
  def shop_destroy
    shop_log_out if shop_logged_in?
    redirect_to "/shops/not_logged_in"
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def login
    shop_logged_in_user
  end
  def count
    return Shop.count
  end
  def index
    @shop3 = Shop.all
  end

  def show
  end

  def new
    @shop = Shop.new
  end
  def edit
    @shop = Shop.find_by(shop_params)
  end
  def update
    @shop = Shop.find_by(id: params[:shop][:id])
    @shop.update(shop_params)
    @shop.save
    redirect_to shops_logged_in_path(shop: @shop)
  end
  def create
    @shop = Shop.new(shop_params)
    @shop.break = true
    @shop.save
    redirect_to sessions_new_path
  end

  def shop_params
    params.require(:shop).permit(:name, :email, :password, :password_confirmatio, :tell, :shopname, :shopadd, :image)
  end
  
  def detail
    @shop = Shop.find_by(:id => params[:shopid])
  end
  helper_method :login
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    logged_in_user
  end
  def index
  end

  def show
    @user = User.find_by(:user_id => params[:user_id])
  end

  def new
    @user = UserHide.new
  end
  def edit
    @user = UserHide.find_by(user_params)
  end
  def update
    @user = UserHide.find_by(params[:user_hide][:id])
    @user.update(user_params)
    redirect_to users_logged_in_path(user: @user)
  end
  def create
    @user = UserHide.new(user_params)
    @user.break = true
    @user.save
    redirect_to sessions_new_path
  end

  def user_params
    params.require(:user_hide).permit(:name, :email, :password, :password_confirmatio,:image)
    
  end
  helper_method :login
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    #クッキー保存
    def log_in(user)
        session[:user_id] = user.id
    end
    #セッション確認
    def current_user
        if session[:user_id]
        @current_user = @current_user || UserHide.find_by(id: session[:user_id])
        end
    end

    def current_user?(user)
        user == current_user
    end
    #ログイン中かの確認
    def logged_in?
        !current_user.nil?
    end
    #ログアウト
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    def taikai 
        @user = UserHide.find_by(id: session[:user_id])
        @user.update(break: false)
        session.delete(:user_id)
        @current_user = nil
    end

    def shop_log_in(shop)
        session[:shop_id] = shop.id
    end
    #セッション確認
    def shop_current_user
        if session[:shop_id]
        @current_shop = @current_shop || Shop.find_by(id: session[:shop_id])
        end
    end

    def shop_current_user?(shop)
        shop == shop_current_user
    end
    #ログイン中かの確認
    def shop_logged_in?
        !shop_current_user.nil?
    end
    #ログアウト
    def shop_log_out
        session.delete(:shop_id)
        @shop_current_user = nil
    end
    def shop_taikai 
        @shop = Shop.find_by(id: session[:shop_id])
        @shop.update(break: false)
        session.delete(:shop_id)
        @shop_current_user = nil
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barbareats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <%= render '/shared/header'%>
</head>
<body>
    <h1>リンク置き場</h1>
    <%= link_to "ホーム画面","/main/show" %>
    <br>
    <%= link_to "ユーザー登録画面","/sessions/new"%>
    <br>
    <%= link_to "ユーザー登録画面","/users/register"%>
    <br>
    <%= link_to "ユーザー2画面","/users/show/2"%>
</body>
</html>

app/views/main/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <%= render '/shared/header'%>
</head>
<body>
    <h1>BarBarEats</h1>
    <h3><%=@home[:welcome]%></h3>
</body>
</html>

app/views/shared/_header.html.erb
<div class=head><%= link_to("BarBarEats", "/main/show", {class: "link"}) %></div>
<div class=pic><%= link_to image_tag('babaekan2.png', size: '50x50'), "/main/show" %></div>
<div class=serch><link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<form method="get" action="#" class="search_container">
<input type="text" size="25" placeholder="キーワード検索">
<input type="submit" formaction="/shops/result"value="&#xf002">

</form></div>
<div class=head2><%= link_to("/sessions/new") do%>
<button>ログイン</button><% end %></div>
<div class=head2><%= link_to("/users/new") do%>
<button>ユーザー新規登録</button><% end %></div>
<div class=head2><%= link_to("/shops/new") do%>
<button>店舗新規登録</button><% end %></div>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6219069591397421"
     crossorigin="anonymous"></script>
<style>
.head{
display: inline-block;
padding-left: 0%;
color: red;
font-size: 50px;
font-weight: bold;
}
.link{
text-decoration: none;
color:red;
}
.pic{
display: inline-block;
}
.head2{
display: inline-block;
float: right;
margin: 10px;
padding: 5px;
}
.serch{
    display: inline-block;
    float: center;
    margin: auto 10%;
}
.search_container{
box-sizing: border-box;
position: relative;
border: 1px solid #999;
padding: 3px 10px;
border-radius: 20px;
height: 2.3em;
width: 260px;
overflow: hidden;
}
.search_container input[type="text"]{
border: none;
height: 2.0em;
}
.search_container input[type="text"]:focus {
outline: 0;
}
.search_container input[type="submit"]{
cursor: pointer;
font-family: FontAwesome;
font-size: 1.3em;
border: none;
background: none;
color: #3879D9;
position: absolute;
width: 2.5em;
height: 2.5em;
right: 0;
top: -10px;
outline : none;
}
</style>

app/views/shops/detail.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= render '/shared/header'%>
    <style>
    div{
        text-align: center;
    }
    </style>
    <title>Document</title>
</head>
<body>
    <div>
    <h2><%= @shop[:shopname]%></h2>
    <% if @shop.image.attached? %>
        <%= image_tag @shop.image, size: '400x300'%>
    <% end %>
    <h3>住所 : <%= @shop[:shopadd]%></h3>
    <h3>電話番号 : <%= @shop[:tell]%></h3>
    </div>
</body>
</html>

app/views/shops/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    
</body>
</html>

app/views/shops/logged_in.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <%= login%>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
    
    <div hidden><%= @shop =Shop.find_by(id:params[:shop])%> </div>
</head>
<body>
    <h1>店舗ページ</h1>
    <% if @shop.image.attached? %>
        <%= image_tag @shop.image, size: '400x300' %>
    <%end%>
    <h3><%= link_to "会員情報編集", shops_setting_url(shop: @shop)%></h3>
    <h3><%= link_to "退会", '/users/break'%></h3>
    <%= link_to "ログアウト", '/shops/not_logged_in' , method: :delete %>
</body>
</html>

app/views/shops/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <h1>店舗新規登録</h1>
    <h3>
    <%= form_for @shop, url: {action: 'create'}  do |f| %>
    <%= f.label :name,"名前" %>
    <br>
    <%= f.text_field :name %>
    <br>
    <%= f.label :shopname,"店舗名" %>
    <br>
    <%= f.text_field :shopname %>
    <br>
    <%= f.label :shopadd,"住所" %>
    <br>
    <%= f.text_field :shopadd %>
    <br>              
    <%= f.label :tell,"電話番号" %>
    <br>
    <%= f.text_field :tell %>
    <br>
    <%= f.label :email,"メールアドレス" %>
    <br>
    <%= f.text_field :email %>
    <br>
    <%= f.label :password,"パスワード" %>
    <br>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation,"パスワード確認" %>
    <br>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "登録" %>
    <% end %>
    </h3>
</body>
</html>

app/views/shops/not_logged_in.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <p>BarBarEatsへようこそ。まずはログインをしてください。</p>
    <%= link_to "ログイン", "/sessions/new"%>
</body>
</html>

app/views/shops/register.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <h1>登録完了</h1>
    <p><%= link_to "ログイン","/sessions/new"%></p>
</body>
</html>

app/views/shops/result.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= render '/shared/header'%>
    <div hidden><%= @shop3 = Shop.all%></div>
    <title>Document</title>
</head>
<body>
<h1>店舗一覧</h1>
    <div class=waku>
    <% @shop3.each do |tenpo|%>
        <div class=yoko>
        <%= tenpo.shopname %>
        <br>
        <div hidden><%= @shoplink = "/shops/detail/"+tenpo.id.to_s %></div>
        <% if tenpo.image.attached? %>
            <%= link_to image_tag(tenpo.image, size: '400x300'), @shoplink %>
        <% end %>
        </div>
    <% end %>
    </div>
</body>
</html>
<style>
.yoko{
    text-align:center;
    width: 50%;
    box-sizing: border-box;
}
.waku{
    display:flex;
    flex-wrap:wrap;
}
</style>

app/views/shops/setting.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <%= login%>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
    <div hidden><%=  @shop =Shop.find_by(id:params[:shop])%></div>
</head>
<body>
    <h1>会員情報変更</h1>
    <h3>
    <%= form_for @shop, url: {action: 'update'} do |f| %>
    <div hideen>
    <%= f.hidden_field :id,:value => @shop.id%>
    </div>
    <%= f.label :name,"名前"%>
    <br>
    <%= f.text_field :name,:value => @shop.name %>
    <br>
    <%= f.label :shopname,"店舗名" %>
    <br>
    <%= f.text_field :shopname,:value => @shop.shopname %>
    <br>
    <%= f.label :shopadd,"住所" %>
    <br>
    <%= f.text_field :shopadd,:value => @shop.shopadd %>
    <br>
    <%= f.label :tell,"電話番号" %>
    <br>
    <%= f.text_field :tell,:value => @shop.tell %>
    <br>
    <%= f.label :email,"メールアドレス" %>
    <br>
    <%= f.text_field :email,:value => @shop.email %>
    <br>
    <%= f.label :password,"パスワード" %>
    <br>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation,"パスワード確認" %>
    <br>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.label :image,"店舗画像" %>
    <br>
    <%= f.file_field :image %>
    <br>
    <%= f.submit "変更" %>
    <% end %>
    <%= link_to "戻る",shops_logged_in_path(shop: params[:shop])%>
</body>
</html>

app/views/shops/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    
</body>
</html>

app/views/users/break.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <h1>退会しますか?</h1>
    <div class=img-wrap2>
    <%= image_tag('babaekan2naki.png',size:'200x200')%>
    </div>
    <p>
    <%= link_to "はい","/users/break_out"%>
    <%= link_to "いいえ","/main/show"%>
    </p>
</body>
</html>
<style>
.img-wrap2 {
    text-align:center;
    
}
</style>

app/views/users/break_out.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <%= taikai%>
    <h1>退会済みです</h1>
    <%= link_to "ホーム画面","/main/index" %>
</body>
</html>

app/views/users/break_zumi.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <h1>退会されています</h1>
</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <h1>BARBAREATS</h1>

</body>
</html>

app/views/users/logged_in.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <%= login%>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
    <div hidden><%= @user =UserHide.find_by(id:params[:user])%> </div>
</head>
<body>
    <h1>ユーザーページ</h1>
    <% if @user.image.attached? %>
        <%= image_tag @user.image, size: '400x300' %>
    <%end%>
    <h3><%= link_to "会員情報編集", users_setting_url(user: @user)%></h3>
    <h3><%= link_to "退会", '/users/break'%></h3>
    <%= link_to "ログアウト", '/users/not_logged_in' , method: :delete %>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <h1>ユーザー新規登録</h1>
    <h3>
    <%= form_for  @user, url: {action: 'create'} do |f| %>
    <%= f.label :name,"名前" %>
    <br>
    <%= f.text_field :name %>
    <br>
    <%= f.label :email,"メールアドレス" %>
    <br>
    <%= f.text_field :email %>
    <br>
    <%= f.label :password,"パスワード" %>
    <br>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation,"パスワード確認" %>
    <br>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "登録" %>
    <% end %>
    </h3>
</body>
</html>

app/views/users/not_logged_in.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <p>BarBarEatsへようこそ。まずはログインをしてください。</p>
    <%= link_to "ログイン", "/sessions/new"%>
</body>
</html>

app/views/users/register.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <h1>登録完了</h1>
    <p><%= link_to "ログイン","/sessions/new"%></p>
</body>
</html>

app/views/users/setting.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <%= login%>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
    <div hidden><%=  @user =UserHide.find_by(id:params[:user])%></div>
</head>
<body>
    <h1>会員情報変更</h1>
    <h3>
    <%= form_for @user, url: {action: 'update'} do |f| %>
    <%= f.hidden_field :id,:value => @user.id%>
    <%= f.label :name,"名前"%>
    <br>
    <%= f.text_field :name,:value => @user.name %>
    <br>
    <%= f.label :email,"メールアドレス" %>
    <br>
    <%= f.text_field :email,:value => @user.email %>
    <br>
    <%= f.label :password,"パスワード" %>
    <br>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation,"パスワード確認" %>
    <br>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.label :image,"画像" %>
    <br>
    <%= f.file_field :image %>
    <br>
    <%= f.submit "変更" %>
    <% end %>
    <%= link_to "戻る",users_logged_in_path(user: params[:user])%>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= render '/shared/header'%>
</head>
<body>
    <h1>user_name : <%=@user[:user_name]%></h1>
    <h3>user_id  : <%=@user[:user_id]%></h3>
    <h3>user_mail  : <%=@user[:user_mail]%></h3>
    <h3>user_pass  : <%=@user[:user_pass]%></h3>
</body>
</html>